site_name: Turtle Quant 1
site_description: All hail the turt.
repo_name: jyjulianwong/Turtle-Quant-1
repo_url: https://github.com/jyjulianwong/Turtle-Quant-1
edit_uri: edit/main/

nav:
  - Home: index.md
  - Optimization: optimization-v1.2.0.md
  - API Reference: reference/

theme:
  name: material
  logo: turtle.webp
  favicon: turtle.webp
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - search.suggest
    - content.code.copy
    - content.action.edit

plugins:
  - search
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_root_heading: true
            show_source: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            merge_init_into_class: true
            separate_signature: true
            show_signature_annotations: true
            signature_crossrefs: true

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ["."]
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jyjulianwong/Turtle-Quant-1

watch:
  - src/turtle_quant_1
  - README.md
