name: Test, Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: ⚙️ Set up repository
        uses: actions/checkout@v3

      - name: ⚙️ Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv
          uv sync --group dev

      - name: 🧪 Run tests
        run: |
          uv run pytest tests/ -v

  build:
    needs: test
    if: github.ref == 'refs/heads/main'
    environment: google-cloud
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.export.outputs.image_tag }}
    steps:
      - name: ⚙️ Set up repository
        uses: actions/checkout@v3

      - name: ⚙️ Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: ⚙️ Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: '${{ vars.TURTLEQUANT1_GCLOUD_PROJECT_ID }}'

      - name: 🔐 Configure Docker authentication
        run: |
          gcloud auth configure-docker ${{ vars.TURTLEQUANT1_GCLOUD_REGION }}-docker.pkg.dev --quiet

      - name: 🏗️ Build Docker image
        run: |
          IMAGE_TAG="${{ vars.TURTLEQUANT1_GCLOUD_REGION }}-docker.pkg.dev/${{ vars.TURTLEQUANT1_GCLOUD_PROJECT_ID }}/${{ vars.TURTLEQUANT1_GCLOUD_PROJECT_ID }}-gar-usea1-docker/turtle-quant-1:0.1.0"
          
          echo "Building image..."
          docker build -t $IMAGE_TAG --platform linux/amd64 -f Dockerfile .

          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: 📤 Push Docker image
        run: docker push $IMAGE_TAG

      - name: 📦 Export image tag for downstream jobs
        id: export
        run: |
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

  deploy:
    needs: build
    environment: google-cloud
    runs-on: ubuntu-latest
    steps:
      - name: ⚙️ Checkout repository
        uses: actions/checkout@v3

      - name: ⚙️ Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: ⚙️ Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: '${{ vars.TURTLEQUANT1_GCLOUD_PROJECT_ID }}'

      - name: ⚙️ Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: ⚙️ Generate terraform.tfvars
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          sed -e "s|{{IMAGE_TAG}}|${{ needs.build.outputs.image_tag }}|g" \
              -e "s|{{TURTLEQUANT1_ENV}}|${{ vars.TURTLEQUANT1_ENV }}|g" \
              -e "s|{{TURTLEQUANT1_GCLOUD_REGION}}|${{ vars.TURTLEQUANT1_GCLOUD_REGION }}|g" \
              -e "s|{{TURTLEQUANT1_GCLOUD_PROJECT_ID}}|${{ vars.TURTLEQUANT1_GCLOUD_PROJECT_ID }}|g" \
              -e "s|{{TURTLEQUANT1_GCLOUD_STB_DATA_NAME}}|${{ vars.TURTLEQUANT1_GCLOUD_STB_DATA_NAME }}|g" \
              -e "s|{{TURTLEQUANT1_ALPHA_VANTAGE_API_KEY}}|${{ secrets.TURTLEQUANT1_ALPHA_VANTAGE_API_KEY }}|g" \
              terraform/p.tfvars.template > terraform/terraform.tfvars

      - name: ⚙️ Terraform Init
        working-directory: ./terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          rm -f .terraform.lock.hcl
          terraform init \
            -backend-config="bucket=${{ vars.TURTLEQUANT1_GCLOUD_PROJECT_ID }}-tfstate-${{ vars.TURTLEQUANT1_GCLOUD_REGION }}" \
            -backend-config="prefix=terraform/state" \
            -upgrade

      - name: ⚙️ Terraform Validate
        working-directory: ./terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: terraform validate

      - name: ⚙️ Import Existing Resources
        working-directory: ./terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          # Import Cloud Run service
          terraform import google_cloud_run_service.app ${{ vars.TURTLEQUANT1_GCLOUD_REGION }}/${{ vars.TURTLEQUANT1_GCLOUD_PROJECT_ID }}/${{ vars.TURTLEQUANT1_GCLOUD_PROJECT_ID }}-run-${{ vars.TURTLEQUANT1_GCLOUD_REGION }}-app || true
          
          # Import Cloud Storage buckets
          terraform import google_storage_bucket.data ${{ vars.TURTLEQUANT1_GCLOUD_STB_DATA_NAME }} || true

      - name: ⚙️ Terraform Plan
        working-directory: ./terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: terraform plan -out=tfplan

      - name: ⚙️ Terraform Apply
        working-directory: ./terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          terraform apply -auto-approve tfplan

      - name: 🧹 Cleanup
        if: always()
        run: |
          rm -f terraform/terraform.tfvars 